### ISSUE TITLE
Question: `embedding a component in another is not allowed` ?

### ISSUE THREAD

**Issue by pojiro** [oiax/tgweb#103]
v5.7, README.md says,

> However, embedding a component in another is not allowed.

but it actually works like following,

```
<nav class="flex items-center justify-center h-10 text-base">
  <tg:component name="switcher/prev_button"></tg:component>
  <div aria-current="page" tg:class="text">
    <tg:data name="text"></tg:data>
  </div>
  <tg:component name="switcher/next_button"></tg:component>
</nav>
```

Above is component, so it includes two components inside itself. 

I think it's common to combine components to create other components, so it would be nice to be able to do this.

**Comment by kuroda** [comment]
That is not allowed in the current version, v0.5.8. In reality, it is possible to reference other components in the template of one component, but there is a risk of circular references.

In the next version (v0.6.0), a mechanism will be introduced in tgweb to detect circular references and the wording on README.md will be revised to "allowed".
