### ISSUE TITLE
Question: `position: absolute` is necessary for switcher and rotator ?

### ISSUE THREAD

**Issue by pojiro** [oiax/tgweb#115]
This question is not negative one, just question. The `position: absolute`s are following,

- https://github.com/oiax/tgweb/blob/v0.6.2/packages/tgweb/lib/tgweb/render_web_page.mjs#L851
- https://github.com/oiax/tgweb/blob/v0.6.2/packages/tgweb/lib/tgweb/render_web_page.mjs#L935

---

Before v0.6.x, the height of `tg:item` in `tg:switcher` was automatically determined by its contents, but with the addition of the feature in v0.6.2, `position: absolute` was applied. Due to this, it became necessary to specify the height **from the outside**, like `tg:body div`. 
(This is because a tag with `position: absolute` exists separately from its enclosing element, so it behaves as if it has no height for the enclosing element.)

This may be a little inconvenient in cases where the height of the content changes dynamically, for example in responsive designs.

**Comment by kuroda** [comment]
With tgweb 0.6.3, the width and height of switcher/rotator body are adjusted automatically.
