### ISSUE TITLE
Feature Request: Container queries support

### ISSUE THREAD

**Issue by pojiro** [oiax/tgweb#122]
Container queries enables more precise control over responsive design than viewports.
Being able to use it may be an advantage for users, so I would like you to consider supporting it. Tailwindcss support it from v3.2. 

- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_container_queries
- https://tailwindcss.com/blog/tailwindcss-v3-2#container-queries

**Comment by kuroda** [comment]
Container queries are already supported.

You can verify this with the following HTML fragment:

```html
<div class="mx-auto w-[25%] bg-red-300 mb-4 text-4xl @container">
  <div class="bg-pri-s p-4">
    <span class="@[240px]:underline">A</span>
  </div>
</div>

<div class="mx-auto lg:w-[50%] grid grid-cols-2 gap-2 text-4xl">
  <div class="bg-green-500 p-4 @container/a">
    <span class="@[240px]/a:underline">B</span>
  </div>
  <div class="bg-blue-500 p-4 @container/b">
    <span class="@[360px]/b:text-white">C</span>
  </div>
</div>
```

**Comment by pojiro** [comment]
> Container queries are already supported.

I didn't realize that the plugin was added to sites/*/tailwind.config.js. I'msorry.

I also confirmed that it can be used. thank you!
