### ISSUE TITLE
Translate README-ja.md on Pages to Japanese

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#126]

**Comment by kaitoukei** [comment]
@kuroda 

質問です。

`README-ja.md` ファイルの121行目に次のように記載されています。
しかし、`my_site/dist/index.html` 内に`<title>` 要素の記述がありません。

```
初期状態では、`my_site/dist/index.html` 内の `<title>` 要素が "No Title" と設定されています。この箇所については後ほど取り上げます。
```

しかし、`src/pages/index.html` の内容を`README-ja.md` ファイルの318-323行目記載の内容に変更すると、`dist/index.html` の4行目に `<title>Greeting</title>` が挿入されます。

`README.md-ja : 318-323
```
<body>
  <h1 class="text-2xl font-bold">Greeting</h1>
  <div class="bg-green-300 p-4">
    <p>Hello, world!</p>
  </div>
</body>
```
この辺りの説明は、`README-ja.md` 記載のままで良いでしょうか？

**Comment by kuroda** [comment]
@kaitoukei 

> 記載のままで良いでしょうか？

このように書かれているということは、現在の記載内容に矛盾あるいは不足があると言うことかと思われます。

「このままで良いか」と尋ねるより、どこに矛盾あるいは不足があるのかを具体的に指摘していただけませんでしょうか。

**Comment by kaitoukei** [comment]
@kuroda 

下記のコメントを矛盾点として書き直しました。

https://github.com/oiax/tgweb/issues/126#issuecomment-1842397431

**Comment by kuroda** [comment]
@kaitoukei 

ありがとうございます。121行目の内容が正しいと信じ込んでいたため、質問の意図が分かりませんでした。

初期状態で `<title>` 要素が出現しないのは（最近の）バグです。先ほど修正しましたので、`npm install tgweb@latest` コマンドで tgweb を最新版（v0.6.7）に上げ、`npx tgweb-init` からやり直してください。

「不足」とされた件ですが、最新版では、`<title>` 要素の中身が「No Title」から「Greeting」に変化します。このことについては、

> `See [below](#managing-the-contents-of-the-head-element) for details.`

のように後述されれているので、追記不要です。

**Comment by kuroda** [comment]
@kaitoukei 

> See below for details.

詳細は後述します。
