### ISSUE TITLE
Translate README-ja.md on Front Matter to Japanese

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#128]

**Comment by kaitoukei** [comment]
@kuroda 

質問です。

`README.md` の 435行目の `* Section header` と 464行目の`### Table headers` は同じものでしょうか？

**Comment by kaitoukei** [comment]
[メモ]

- `Table headers` の中で、テーブル名のリストが書かれていますが、`main` がありませんが、追加したほうが良いでしょうか？
- 定義済みプロパティに値を設定する場合は、`[main]` テーブルに記述すれば良いでしょうか？
- 下記の箇所の意味がよく理解できません。
`README.md : 485-486`
  ```
  In the area before the first table header in the front matter block, set the value of
  _predefined properties_.
  ```

**Comment by kaitoukei** [comment]
[メモ]

`my_site/src/pages/index.html` に次のように記述します。

```
---
[main]
title = "Our Mission"
html-class="bg-blue-200"
---
<body>
  <h1 class="text-2xl font-bold">
    <tg:prop name="title"></tg:prop>
  </h1>
  <p>sceme:<tg:prop name="scheme"></tg:prop></p>
  <p>host:<tg:prop name="host"></tg:prop></p>
  <p>port:<tg:prop name="port"></tg:prop></p>
  <p>url:<tg:prop name="url"></tg:prop></p>
  <p>root-url:<tg:prop name="root-url"></tg:prop></p>
  <p>layout:<tg:prop name="layout"></tg:prop></p>
  <p>html-class:<tg:prop name="html-class"></tg:prop></p>
  <div class="bg-green-300 p-4">
    <p>Hello, world!</p>
  </div>
</body>
```

ブラウザの表示
![image](https://github.com/oiax/tgweb/assets/16838259/8459256c-9637-422a-a71e-243d444cbbb0)

- `<tg:prop name="url">` の部分が何も表示されません。

**Comment by kuroda** [comment]
@kaitoukei 

> `README.md` の 435行目の `* Section header` は、464行目から説明している`### Table headers` のことでしょうか？

はい、そうです。「Section header」と呼んでいた概念を途中から「Table header」と呼ぶように変えました。`README.md` 側も一緒に修正してください。他にも修正漏れがあるかもしれません。

**Comment by kuroda** [comment]
@kaitoukei 

> `Table headers` の中で、テーブル名のリストが書かれていますが、`main` がありませんが、追加したほうが良いでしょうか？

追加してください。`README.md` の方は修正済みです。

> 定義済みプロパティに値を設定する場合は、`[main]` テーブルに記述すれば良いでしょうか？

はい。

> 下記の箇所の意味がよく理解できません。

`[main]` テーブルを導入する前の記述が残っていました。`README.md` を修正してあります。

**Comment by kuroda** [comment]
@kaitoukei 

> `<tg:prop name="url"></tg:prop>` の部分が何も表示されません。

バグです。`npx tgweb-server` を起動した直後は表示されるのですが、ページテンプレートを修正すると消えてしまいます。

最新の `tgweb@0.6.8` で修正されています。
