### ISSUE TITLE
Translate README-ja.md on Images to Japanese

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#135]

**Comment by kaitoukei** [comment]
@kuroda 

質問です。

`README.md` の754-755行目に次のように書かれています。
```
If the `src` attribute of the `<img>` element contains the relative path of the image file,
the image will be embedded in the page.
```
764行目には、次のように書かれています。
```
Note that the value of the `src` attribute is the _absolute_ path of the image file.
```
この2つは矛盾しているかと思います。
754行目の `relative path` を `absolute path` と直して良いでしょうか。

**Comment by kaitoukei** [comment]
@kuroda 

`README.md` を参考に、`img` 要素と背景画像を試してみました。

`img` 要素の方は表示されるのですが背景画像の方が表示されません。

私では原因を突き止めることができません。
お手数をおかけしますが、お時間のある時で結構ですのでお力を貸してください。

htmlファイルは下記です。
【html】`my_site/src/pages/foo/bar.html`
```html
<body>
  <p>img 要素</p>
  <div>
    <img src="/images/smile.png" alt="Smile face">
  </div>
  <p class="mt-4">画像背景</p>
  <div class="bg-[url(../images/smile.png)]"></div>
</body>
```

サイトのツリーは下記です。
![image](https://github.com/oiax/tgweb/assets/16838259/608093a3-f28a-40e2-8aa2-d0bc6546e8c4)

ブラウザ画面
![image](https://github.com/oiax/tgweb/assets/16838259/8c88a92f-4a40-4044-87a3-97da296919c5)

**Comment by kuroda** [comment]
@kaitoukei 

> 背景画像の方が表示されません。

`<div class="bg-[url(../images/smile.png)]"></div>` という書き方だと、`<div>` 要素の高さが0になります。

`<div class="h-[160px] bg-[url(../images/smile.png)]"></div>` のように高さを与えてみてください。

**Comment by kaitoukei** [comment]
@kuroda 

表示されました。
ありがとうございます。

**Comment by kuroda** [comment]
@kaitoukei 

> 754行目の `relative path` を `absolute path` と直して良いのでしょうか。

はい。直してください。
