### ISSUE TITLE
Translate README-ja.md on Fonts and Icons to Japanese

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#139]

**Comment by kaitoukei** [comment]
@kuroda 

質問です。

`README.md` の931-963 行目辺りを参考に、Material Symbolsを使用する下記のサンプルを作ってみました。

`sample.html`
```
---
[main]
title = "sample1"
[font.material-symbols]
outlined = true
rounded = { fill: 0, wght: 200, grad: 0, opsz: 24 }
rounded.strong = { fill: 1, wght: 400, grad: 0, opsz: 24 }
rounded.bold = { fill: 0, wght: 700, grad: 0, opsz: 24 }
---
<body>
  <h1>sample1</h1>
  <span class="material-symbols-outlined">home</span>
  <span class="material-symbols-rounded">delete</span>
  <span class="material-symbols-sharp">shopping_bag</span>
  <span class="material-symbols-rounded.strong">star</span>
</body>
```

ブラウザの表示が次のようになってしまいます。
![image](https://github.com/oiax/tgweb/assets/16838259/fdf4a671-f094-4903-9782-6fd4dfff35e2)

このとき、コンソールに次のように表示されます。
```
Found a syntax error in the front matter block: src/pages/fuji/sample1.html
-----------------------------------------------------------------------------
{ line: undefined }
...
^
-----------------------------------------------------------------------------
```
対処方法を教えていただければと思います。
よろしくお願いいたします。

**Comment by kuroda** [comment]
@kaitoukei 

`README.md` の方に間違いがありますね。

```
誤 { fill: 0, wght: 200, grad: 0, opsz: 24 }
正 { fill = 0, wght = 200, grad = 0, opsz = 24 }
```

英語版の方も修正してください。

それから、`rounded.bold` を使いたい場合、`<span class="material-symbols-rounded strong">star</span>` のように書くのが正しいです。しかし、こちらは未実装の可能性があります。

**Comment by kaitoukei** [comment]
@kuroda 

エラーになってしまいます。
下記はOKのようです。
```
rounded = { fill = 0, wght = 200, grad = 0, opsz = 24 }
```
下記がエラーになるようです。
```
rounded.bold = { fill = 1, wght = 400, grad = 0, opsz = 24 }
rounded.strong = { fill = 0, wght = 700, grad = 0, opsz = 24 }
```

**Comment by kuroda** [comment]
@kaitoukei 

確かに、`rounded` と `rounded.bold` は共存できないですね。`README.md` が間違っています。

直しますので、少々お待ちください。

**Comment by kuroda** [comment]
@kaitoukei 

「Variants」の項に書かれている内容は、仕様自体に問題があることが判明しました。

いったん翻訳範囲から除外してください。

**Comment by kaitoukei** [comment]
@kuroda 

> いったん翻訳範囲から除外してください。

承知いたしました。

**Comment by kuroda** [comment]
`README.md` では「Noto Sans Japanese」という名前のフォントが存在するかのように書かれていますが、正しいフォント名は「Noto Sans JP」です。

Google Fonts のフォント一覧に出てくる見出しとフォント名が異なるケースがあります。

修正をお願いします。
