### ISSUE TITLE
Translate README-ja.md on Layouts to Japanese

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#141]

**Comment by kaitoukei** [comment]
[メモ]

`<tg:insert>` 要素は、ページコンテンツのトップレベルに記述する。

下記はOK。
```
---
[main]
layout = "product"
title = "Product 1"
---
<tg:insert name="badges"><span>A</span><span>B</span></tg:insert>
<div>
  <h1>Product 1</h1>
  <p>Description</p>
</div>
<tg:insert name="remarks">This product is very <em>fragile</em>.</tg:insert>
```

下記はNG。
```
---
[main]
layout = "product"
title = "Product 1"
---
<div>
  <h1>Product 1</h1>
  <p>Description</p>
  <tg:insert name="badges"><span>A</span><span>B</span></tg:insert>
</div>
<tg:insert name="remarks">This product is very <em>fragile</em>.</tg:insert>
```

**Comment by kaitoukei** [comment]
@kuroda 

`<tg:if-complete>` に関する確認です。

例示されているサンプル（`src/layouts/message.html` と `src/pages/home.html`) は「 However,if the following two conditions are not met, the entire element is deleted」という記述に関するサンプルかと思います。できれば、「Normally, the <tg:if-complete> element in a layout is simply replaced with its content. 」の方のサンプルもあったほうが良いように思います。

**Comment by kuroda** [comment]
@kaitoukei 

> sample1はOKですが、sample2はNG。

その認識で合っています。

> できれば、「Normally, the tg:if-complete element in a layout is simply replaced with its content. 」の方のサンプルもあったほうが良いように思います。

英語版と日本語版にサンプルを追加してください。

**Comment by kaitoukei** [comment]
@kuroda 

>> できれば、「Normally, the tg:if-complete element in a layout is simply replaced with its content. 」の方のサンプルもあったほうが良いように思います。

> 英語版と日本語版にサンプルを追加してください。

承知いたしました。
