### ISSUE TITLE
Translate README-ja.md on Wrappers to Japanese

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#145]

**Comment by kaitoukei** [comment]
@kuroda 

質問です。

`README.md` の1400行目に次のように書かれています。

```
The only thing you should do is take the `layout` attribute off the page.
```

しかし、その下のサンプルコードには `layout = "common"` の記述があります。
実際にコードを記述して試してみると、`layout = "common"` の有無に関係なくラッパーに書かれていることはページに適用されるようです。

1400行目の `The only thing you should do is take the `layout` attribute off the page.` の意味がよくわかりません。ご教示ください。

**Comment by kuroda** [comment]
@kaitoukei 

金曜日13:30からの定例会議までに考えておきます。

**Comment by kaitoukei** [comment]
@kuroda 

> 金曜日13:30からの定例会議までに考えておきます。

よろしくお願いいたします。

Teamgenikの方の「issue ##4724 [craft] プロパティの「型」のヘルプ文書に追記する 」をやっています。

**Comment by kaitoukei** [comment]
@kuroda 

`README-ja.md` のラッパーの部分を書いてみました。
ご確認ください。
ブランチは、`kaitoukei/issue-145-translate-readme-ja-on-wrappers-to-ja` です。
ご確認いただいた後、英訳して `README.md` の Wrappers の部分を完成させる予定です。

**Comment by kuroda** [comment]
@kaitoukei 

確認し、コメントしました。

**Comment by kaitoukei** [comment]
@kuroda 

ありがとうございました。
ご指摘事項を修正し、日本語版で変更した部分を英訳してPRをだします。
