### ISSUE TITLE
Translate README-ja.md on Segments to Japanese

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#147]

**Comment by kaitoukei** [comment]
@kuroda 

確認です。

`README-ja.md` には `### Segment layers` に関する記述がありますが、`README.md` にはありません。
`README.md` をベースに翻訳をすれば良いでしょうか？

**Comment by kaitoukei** [comment]
@kuroda 

質問です。

```
A _segment_ is a template file that can be embedded in pages, layouts or segments.
Segments cannot be embedded in templates other than these types, such as articles,
wrappers, segments or components.
```

`README.md` の1558-1560行目に上記のように書かれています。
2つ目のパラグラフの `segments or components` の `segments` は削除して良いでしょうか？

**Comment by kuroda** [comment]
> 削除して良いでしょうか？

はい。
