### ISSUE TITLE
Translate README-ja.md on Components to Japanese

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#153]

**Comment by kuroda** [comment]
> ここでレイアウトが出てくると少し混乱するので削除したいのですがいかがでしょうか？

削除してください。

**Comment by kaitoukei** [comment]
@kuroda 

度々の質問ですみません。

`README.md` の 1778行目に次の記述があります。

```
<i class="fas fa-smile"></i>
```

しかし、画面上にスマイルアイコンは表示されません。
`tgweb` の `README.md` の中で、Font Awesome を使用しているのはこの箇所だけです。

対応はいかがいたしましょうか。

**Comment by kuroda** [comment]
> 対応はいかがいたしましょうか。

Material Symbols のアイコンを使ってください。
