### ISSUE TITLE
Italics in English translate to 「」 in Japanese

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#162]

**Comment by kaitoukei** [comment]
@kuroda 

質問です。

先週の定例会議で、『英語の斜体は日本語では「」に変える』というご指示がありました。
「インストールと初期化」セクションなどを拝見すると、英語の斜体の箇所は、`<ins>` と `</ins>` で囲んでいます。
どちらにしましょうか？

**Comment by kaitoukei** [comment]
@kuroda 

`<em>` だと斜体になってしまいます。
確か、日本語の場合は斜体はあまり使わないのでかぎかっこ（「」）にするというお話だったように思います...

**Comment by kuroda** [comment]
英語は em で、日本語はカギカッコとしてください。

**Comment by kaitoukei** [comment]
現在、英語はアンダースコアで囲んでいます。
これを`<em>` にするという理解で良いでしょうか？

**Comment by kaitoukei** [comment]
> 「インストールと初期化」セクションなどを拝見すると、英語の斜体の箇所は、`<ins>` と `</ins>` で囲んでいます。

この表現が誤解されてしまったかもしれません。

正しくは、下記です。
『英語（README.md)は、アンダースコアで囲んでいます。同じ箇所を日本語（README-ja.md)では、`<ins>` と `</ins>` で囲んでいます。』

**Comment by kuroda** [comment]
アンダースコアでお願いします。
