### ISSUE TITLE
Translate README-ja.md on Dynamic Elements to Japanese

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#165]

**Comment by kaitoukei** [comment]
質問が２つ有ります。

**質問１**
`README.md` の2355行目と2393行目に`__modal__` と `__toggler__` のように2個のアンダースコアで囲まれた単語があります。アンダースコア1個 ではなく2個で良いのでしょうか？

```
We call an HTML element with the `tg:modal` attribute a __modal__.
```

```
We call an HTML element with the `tg:toggler` attribute a __toggler__.
```

**質問2**
「動的要素」セクションの下記のサブセクション名はREADME-ja.mdでは英語のままの方が良いでしょうか。「モーダル」、「トグラー」、「スイッチャー」のようにカタカナにした方が良いでしょうか？

  * [Modal](#modal)
  * [Toggler](#toggler)
  * [Switcher](#switcher)
  * [Rotator](#rotator)
  * [Carousel](#carousel)
  * [Scheduler](#scheduler)
  * [Tram](#tram)
  * [Notes on Alpine.js](#nodes-on-alpinejs)

**Comment by kuroda** [comment]
@kaitoukei 

回答1: アンダースコア1個に修正してください。

回答2: 英語のままとしてください。

**Comment by kaitoukei** [comment]
@kuroda 

追加で質問が1点あります。

**質問3**
`README.md` の2548−2552行目のサンプルを作成して試してみましたが、フェードイン／フェードアウトをあまり実感できません。` tg:transition-duration` の値をいろいろ変えてみましたが変化しません。2538-2572行目のサンプルと同じような動作です。

```html
<div tg:switcher tg:interval="5000" tg:transition-duration="750">
  ...
</div>
```

**Comment by kaitoukei** [comment]
@kuroda 

五月雨式の質問で申し訳ございません

**質問4**
`README.md` の2565−2572行目に書かれている `tg:paginator` のサンプルを次のように作成してみました。

```
<body>
  <div tg:switcher>
    <div tg:body>
      <div tg:item>A</div>
      <div tg:item>B</div>
      <div tg:item>C</div>
      <div tg:item>D</div>
      <div tg:item>E</div>
    </div>
    <nav>
      <button type="button" tg:paginator></button>
    </nav>
  </div>
</body>
```
ブラウザには、「A」という1文字しか表示されません。
サンプルの作り方が間違っているのでしょうか？

**Comment by kuroda** [comment]
@kaitoukei 

> ブラウザには、「A」という1文字しか表示されません。

`tg:paginator` のボタンが表示されない、という意味ですね？

こちらでも再現しました。バグです。

**Comment by kaitoukei** [comment]
@kuroda 

> tg:paginator のボタンが表示されない、という意味ですね？

おっしゃる通りです。

**Comment by kuroda** [comment]
@kaitoukei 

バグではなく、ドキュメントの不備でした。

```html
<button type="button" tg:paginator></button>
```

のように書いただけでは、単なる `<button></button>` 要素が作られるだけなのでユーザーには何も見えません。CSSでスタイルを指定する必要があります。例えば、

```html
<button
  tg:paginator
  class="rounded-full w-6 h-6 mx-1 bg-gray-500"
></button>
```

このようにすると丸いボタンが現れます。さらに、次のようにするとUIが洗練されます。

```html
<button
  tg:paginator
  class="rounded-full w-6 h-6 mx-1 opacity-50"
  tg:normal-class="bg-teal-400 hover:opacity-75"
  tg:current-class="bg-orange-400 cursor-default"
  tg:disabled-class="bg-gray-400 cursor-default"
></button>
```

**Comment by kaitoukei** [comment]
@kuroda 

上記の説明を追加するという対応で良いでしょうか？

**Comment by kuroda** [comment]
@kaitoukei 

> 上記の説明を追加するという対応で良いでしょうか？

説明を追加してください。文章とコード例は適宜工夫してください。

**Comment by kuroda** [comment]
@kaitoukei 

switcher/rotator に関連するバグを修正して、tgweb 0.8.1 をリリースしました。このバージョンに基づいて動作確認をお願いします。

**Comment by kaitoukei** [comment]
@kuroda 

> switcher/rotator に関連するバグを修正して、tgweb 0.8.1 をリリースしました。このバージョンに基づいて動作確認をお願いします。

バグの内容を教えてください。

**Comment by kaitoukei** [comment]
【メモ】

`README.md` の 2861-2862行目に次のように書かれていますが、
```
Thanks to the `transition duration-500` included in the base class, the effect of `opacity-100` is
applied gradually over a period of 0.5 seconds.
```

下記のように思います。
```
Thanks to `transition duration-[2000ms]` included in the `tg:0` attribute, the effect of `opacity-100` is applied gradually over 0 seconds.
```

- base class ではなく、`tg:0` attibute
- サンプルコードは、`500` ではなく`[2000ms]`となっている
