### ISSUE TITLE
Translate README-ja.md on Embedding Teamgenik Mini-apps to Japanese

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#169]

**Comment by kuroda** [comment]
@kuroda 

TeamGenik 上でミニアプリの `id` を調べる方法について、英語版 README.md に記載する。

**Comment by kaitoukei** [comment]
@kuroda 

「ミニアプリの埋め込み」について一通り日本語に翻訳しました。

なお、下記の作業が残っています。

- `npx tgweb-push` コマンドが実行不可のため、サンプルの動作確認が未だです。
- TeamGenik 上でミニアプリの `id` を調べる方法については、英語版 README.md 記載後に翻訳します。
