### ISSUE TITLE
[README] Add "What can be embedded in what?"

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#191]
Add after "Articles."

**Comment by kaitoukei** [comment]
@kuroda 

セグメントを埋め込むことができるテンプレートに関する質問です。
tgweb と teamgenik の間で次の差異があります。

- セグメントをレイアウトに埋め込む
  - tgweb : ◯
  - teamgenik : ✕
- セグメントをページのラッパーに埋め込む
  - tgweb : ✕
  - teamgenik : ◯

どちらが正しいでしょうか？

**Comment by kuroda** [comment]
@kaitoukei 

> どちらが正しいでしょうか？

tgweb に合わせてください。

TeamGenik で実装が間違っている点について、Bug として issue を起票してください。

**Comment by kaitoukei** [comment]
@kuroda 

teamgenik の issue#5502 をリオープンし追加しました。

https://github.com/oiax/teamgenik/issues/5502#issuecomment-2172375428
