### ISSUE TITLE
Incorrect output if there are line breaks between multiple <tg:data> elements

### ISSUE THREAD

**Issue by kaitoukei** [oiax/tgweb#196]
If you write src as follows, the output will look like dist and web browser.

**src**
```
---
[main]
title="prop_embed"
[data]
x="a"
y="c"
---
<p class="p-2 text-red-500">Hello, world!</p>
<tg:data name="x"></tg:data>
<tg:data name="y"></tg:data>
```

**dist**
```
  <body>
    <p class="p-2 text-red-500">Hello, world!</p>
    a
    c
  </body>
```
**web browser**
```
a c
```

<hr>

Note that spaces are not output when written as follows.
**src**
```
<tg:data name="x"></tg:data><tg:data name="y"></tg:data>
```
**dist, web browser**
```
ac
```

**Comment by kuroda** [comment]
@kaitoukei 

I think the reported behavior is fine.

Is there a contradiction with the description in README.md?

If you want to prevent the space between "a" and "c" from being displayed in the browser, write it like this:

```html
<p class="p-2 text-red-500">Hello, world!</p>
<div class="flex">
  <span><tg:data name="x"></tg:data></span>
  <span><tg:data name="y"></tg:data></span>
</div>
```

**Comment by kaitoukei** [comment]
@kuroda 

This phenomenon is not a bug, so close it.
The reason I registered this issue was because of Teamgeik's guide and differences.

Create the following in Teamgeik's tree editor.

**Tree editor**
![image](https://github.com/user-attachments/assets/b8c7dd0c-0968-4434-ba28-34dee4b2d29d)

The raw source will then look like the following.  This is the same as `src` in `tgweb` above.

**Raw source**
```
<p>Hello, world!</p>
<tg:data name="x"></tg:data>
<tg:data name="y"></tg:data>
```

The page source and preview will look like this.

**page source**
```
<body><p>Hello, world!</p>ac</body>
```

**Preview**
```
Hello, world!
ac
```

Thus, in Teamgeik, if you write `tg:data x`, `tg:data y` and several nodes in succession, there will be no space between them in the preview.

I think this is not a `tg:data` specific specification, but a node specification in Teamgeik.
Perhaps that should be mentioned in the Teamgeik guide.
