### ISSUE TITLE
Error Due to Default Port 3000 in Use

### ISSUE THREAD

**Issue by ysaito8015** [oiax/tgweb#58]
I followed the README instructions; however, the default port 3000 was already in use, leading to an error. It would be helpful to include guidance on specifying an alternative port when such an issue arises.

https://github.com/oiax/tgweb/blob/c43ca0a1bbc8a3d1d308c00dce504fa10821c4e9/README.md?plain=1#L89

**Comment by kuroda** [comment]
See https://github.com/oiax/tgweb/issues/59#issuecomment-1518534088
