### ISSUE TITLE
tgweb-server Didn't Start on Specified Port Despite Changing Predefined Properties

### ISSUE THREAD

**Issue by ysaito8015** [oiax/tgweb#59]
I followed the README. Even after modifying the predefined properties port to a value 3001 distinct from 3000, `tgweb-server` did not start with the selected port.

https://github.com/oiax/tgweb/blob/c43ca0a1bbc8a3d1d308c00dce504fa10821c4e9/README.md?plain=1#L478

**Comment by kuroda** [comment]
You should set the environment variable `PORT` to change the tgweb server's port:

```bash
PORT=3001 npx tgweb-server my_site
```

This feature is undocumented. README.md needs to be fixed.
