### ISSUE TITLE
Feature Request: Add "Draft" True/False Setting in Front Matter Like HUGO

### ISSUE THREAD

**Issue by ysaito8015** [oiax/tgweb#61]
I followed the README instructions and would appreciate the inclusion of a "draft" true/false setting in the front matter, similar to the functionality provided by HUGO.

**Comment by kuroda** [comment]
https://gohugo.io/content-management/front-matter/#draft

**Comment by kuroda** [comment]
* The `--renderDrafts` option should have the same effect as the Hugo's option of the same name.
* `<tg:link>` and `<tg:links>` should ignore draft articles.

**Comment by kuroda** [comment]
Closed by bee5e70425c744b122fdb2b29e19202418e33561
