### ISSUE TITLE
Material Symbols Font Not Displaying

### ISSUE THREAD

**Issue by ysaito8015** [oiax/tgweb#63]
The Material Symbols font is not being displayed properly.

https://github.com/oiax/tgweb/blob/c43ca0a1bbc8a3d1d308c00dce504fa10821c4e9/README.md?plain=1#L841

**Comment by kuroda** [comment]
In the original spec, Material Symbols were available when the predefined property `font-material-symbols` was set to `true`.

I rewrote the README.md with the intention of introducing `material-symbols` in the `font` table, but forgot to implement it and released a new version.

For now, add the following line to the top of `site.toml`.

```toml
font-material-symbols = true
```

I will incorporate the spec changes into tgweb in the next version.
