### ISSUE TITLE
Feature Request: Enable adding classes to `html` tag

### ISSUE THREAD

**Issue by pojiro** [oiax/tgweb#81]
I'd like to use `scroll-smooth` class, https://tailwindcss.com/docs/scroll-behavior#adding-smooth-scrolling.

[The MDN description](https://developer.mozilla.org/ja/docs/Web/CSS/scroll-behavior) of this class says that it can be used with any tag. However, as far as I have confirmed with chrome, it does not seem to work unless it is given to `html` tag.

I imagine this is why the `html` tag is used as [an example in the explanation of tailwindcss](https://tailwindcss.com/docs/scroll-behavior#adding-smooth-scrolling).

**Comment by kuroda** [comment]
@pojiro 

No, the current spec does not allow this.

Please rewrite the title and body of this issue as a feature request.

**Comment by pojiro** [comment]
Thank you for your explanation!!
