### ISSUE TITLE
Feature Request: animated `tg:paginator`

### ISSUE THREAD

**Issue by pojiro** [oiax/tgweb#83]
carousel `tg:prev`, `tg:next` button has animation, but `tg:paginator` doesn't.

![Peek 2023-07-07 08-54](https://github.com/oiax/tgweb/assets/4096956/ae48fb80-3dec-43fa-8091-27a5972ac61f)

can we make it animated? like,

![Peek 2023-07-07 09-02](https://github.com/oiax/tgweb/assets/4096956/c2f2865f-ed8d-437d-af88-fb181e7dca9e)

ref. https://jtcw.jp/2021/

**Comment by kuroda** [comment]
@pojiro 

I believe that the user interface you cite as an example is a type of carousel.

Already, a tgweb carousel should be able to display N images side by side horizontally by making the width of the carousel frame N times the width of the carousel body. Try that.

However, I have only confirmed that it works with 2 images myself.

**Comment by pojiro** [comment]
@kuroda thx for your quick rep.

> Already, a tgweb carousel should be able to display N images side by side horizontally by making the width of the carousel frame N times the width of the carousel body. Try that.

yap, i already tried that and that works fine.
i just mentioned about animation, like `tg:prev/next`. we would be happy to make `tg:paginate` animatied.

thank you

**Comment by kuroda** [comment]
@pojiro 

My apologies. I misunderstood the purpose of your proposal. We will consider whether it is feasible.

**Comment by kuroda** [comment]
@pojiro 

I have considered the feasibility of your proposal.

I think it is feasible, but would likely require a major change in the way the carousel is implemented internally.

It may take some time.

**Comment by kuroda** [comment]
@pojiro 

With the recent release of `v0.5.3`, your suggestion has been realized.

The changes in implementation were not as significant as I had originally thought.

**Comment by pojiro** [comment]
@kuroda 

i appreciate your quick implementation. i wiil check it tomorrow, thank you.

**Comment by pojiro** [comment]
@kuroda i confirmed this new feature behaviour with 0.5.3. thanks!!
