### ISSUE TITLE
Feature Request: fade-in, fade-out image transition

### ISSUE THREAD

**Issue by pojiro** [oiax/tgweb#91]
Like the hero image of https://akekure-beans.com/, it would be nice if tgweb had a fade-in/fade-out function for the image.
We may need to use CSS `@keyframes` from tailwind to achieve this.

relates. 

- https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes
- https://tailwindcss.com/docs/animation#using-custom-values

**Comment by kuroda** [comment]
Tgweb version 0.6.2 introduces the `tg:transition-duration` attribute for switchers and rotators.

This attribute can be used to switch between images with a fade-in/fade-out effect.

```html
<div tg:rotator tg:interval="5000" tg:transition-duration="750">
  <div tg:body>
    <div tg:item><img src="/images/a.png"></div>
    <div tg:item><img src="/images/b.png"></div>
    <div tg:item><img src="/images/c.png"></div>
  </div>
</div>
```
