### ISSUE TITLE
Feature Request: tgweb-server, support providing svg'z' file

### ISSUE THREAD

**Issue by pojiro** [oiax/tgweb#97]
browser can GET svg files from tgweb-server, but it cannot GET svgz files.

**Comment by pojiro** [comment]
@kuroda 

Thanks for your quick fix.

On 0.5.5, browser can get svgz, but following happens.

![image](https://github.com/oiax/tgweb/assets/4096956/9811e7d4-e558-496c-8295-2815ac4fb351)

svgz is gzip commpressed, so we need 'Content-Encoding: gzip' header on server response ?

**Comment by kuroda** [comment]
@pojiro 

Could you provide a sample `svgz` file?

**Comment by pojiro** [comment]
@kuroda 
Could you ask @megumi-takakura ? She made 'pattern_sikaku.svgz' for POPUP_STORE.
